### ISSUE TITLE
To-Do_list Milestone 2 Issues

### ISSUE THREAD

**Issue by rosemutai** [microvese-projects/ToDoList#4]
@Bennyjoez Great job so far for implementing the requirements!🏆. However, there are a few issues I will advise you to check.

- Fix the indexing bug to ensure that the index of the recently added task, reflects the length of the tasks array at the time of adding it.

**Comment by Bennyjoez** [comment]
Thank you for the review @rosemutai I have implemented the changes and the app is working as expected. 🏆
